trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: fitnessapp
  imageTag: $(Build.BuildId)

steps:

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: Install Node.js

# Install Dependencies
- script: |
    npm install
  displayName: Install Dependencies

# Build & Push Image to ACR
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: Dockerfile
    containerRegistry: acr-connection
    tags: |
      $(imageTag)
      latest

# Deploy to AKS
- task: KubernetesManifest@1
  displayName: Deploy to AKS
  inputs:
    action: deploy
    kubernetesServiceConnection: aks-connection
    namespace: default
    manifests: |
      app-deployment.yaml
      configmap.yaml
      mongodb-deployment.yaml
    containers: |
      ashutoshregistry.azurecr.io/$(imageRepository):$(imageTag)

# Slack Notification
- task: Bash@3
  displayName: Slack Notification
  condition: always()
  inputs:
    targetType: inline
    script: |
      if [ "$(Agent.JobStatus)" = "Succeeded" ]; then
        MESSAGE="✅ Pipeline SUCCESS | Repo: $(Build.Repository.Name) | Build: $(Build.BuildNumber)"
      else
        MESSAGE="❌ Pipeline FAILED | Repo: $(Build.Repository.Name) | Build: $(Build.BuildNumber)"
      fi

      curl -X POST \
      -H "Content-Type: application/json" \
      --data "{\"text\":\"$MESSAGE\"}" \
      "$SLACK_WEBHOOK_URL"
  env:
    SLACK_WEBHOOK_URL: $(SLACK_WEBHOOK_URL)