apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7-jammy
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"   # 🔥 very low → OOM
              cpu: "200m"
          volumeMounts:
            - name: ashutosh-vol
              mountPath: /data/db
      volumes:
        - name: ashutosh-vol
          emptyDir:
            sizeLimit: "128Mi"
