apiVersion: v1
kind: persistentVolume
metadata:
  name: fitness-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  prersistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/general
    server: 13.204.82.236
